tunein/apps/tunein_web/lib/tunein_web/router.ex
defmodule TuneinWeb.Router do
  use TuneinWeb, :router

  import TuneinWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TuneinWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TuneinWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TuneinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      get "", PageController, :index

      live_dashboard "/dashboard", metrics: TuneinWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser


    end
  end

  ## Authentication routes

  scope "/users", TuneinWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register", UserRegistrationController, :new
    post "/register", UserRegistrationController, :create
    get "/log_in", UserSessionController, :new
    post "/log_in", UserSessionController, :create
    get "/reset_password", UserResetPasswordController, :new
    post "/reset_password", UserResetPasswordController, :create
    get "/reset_password/:token", UserResetPasswordController, :edit
    put "/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/users", TuneinWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/settings", UserSettingsController, :edit
    put "/settings", UserSettingsController, :update
    get "/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/users", TuneinWeb do
    pipe_through [:browser]

    delete "/log_out", UserSessionController, :delete
    get "/confirm", UserConfirmationController, :new
    post "/confirm", UserConfirmationController, :create
    get "/confirm/:token", UserConfirmationController, :edit
    post "/confirm/:token", UserConfirmationController, :update
  end
end

tunein/apps/tunein_web/lib/tunein_web/views/layout_view.ex
defmodule TuneinWeb.LayoutView do
  use TuneinWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

tunein/apps/tunein_web/lib/tunein_web/templates/layout/_user_menu.html.heex
<!--
  <ul>
  <%= if @current_user do %>
    <li><%= @current_user.email %></li>
    <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
    <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
  <% else %>
    <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
    <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
  <% end %>
  </ul>
-->


<ul>
  <%= if @current_user do %>
  <li>
    <%= link to: Routes.user_session_path(@conn, :delete), method: :delete do %>
    <button class="btn btn-primary"><p style="color:white;">log out</p></button>
    <% end %>
  </li>

  <li>
    <%= link to: Routes.user_settings_path(@conn, :edit) do %>
    <button class="btn btn-primary"><p style="color:white;">Settings</p></button>
    <% end %>
  </li>

  <% else %>

  <li>
    <%= link to: Routes.user_session_path(@conn, :new) do %>
    <button class="btn btn-primary"><p style="color:white;">Log in</p></button>
    <% end %>
  </li>

  <li>
    <%= link to: Routes.user_registration_path(@conn, :new) do %>
    <button class="btn btn-primary"><p style="color:white;">Register</p></button>
    <% end %>
  </li>

  <% end %>
</ul>

tunein/apps/tunein_web/lib/tunein_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

tunein/apps/tunein_web/lib/tunein_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

tunein/apps/tunein_web/lib/tunein_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Tune In 🎵"%>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="sectionheader">
        <nav>
          <%!--
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          --%>
          <%= render "_user_menu.html", assigns %>
        </nav>
        <a href="/../../../" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/tunein.jpg")} style="height: 60px; width: 136.22px;" >
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

<a href="index.html"></a>